### PR TITLE
Unified generation outputs

### PR DESCRIPTION
**Pull request by jonathanhecl**
Unified generation outputs
And added the tokens in the response.

### CODE REVIEW

**Comment by jonathanhecl** [comment]
Create a new tag for this version :)

**Comment by xyproto** [comment]
This is great, and thanks for the PR!

It is important to me that existing programs that uses `ollamaclient` can continue to use the same API.

So, instead of:

```go
generatedOutput, err := oc.GetOutput(prompt)
[...]
output := generatedOutput.Response
```

And:

```go
generatedOutput := oc.MustOutput(prompt)
[...]
output := generatedOutput.Response
```

Could perhaps `oc.GetOutput` and `oc.MustOutput` keep the same return types as before, but new methods be added?

For instance `oc.GetResult` and `oc.MustResult`?

**Comment by jonathanhecl** [comment]
Yes, it can look like this. However, I am a bit worried that there are 3 endpoints in ollama to get answers, and I don't know when to use one or the other.

/chat/completions (brings "choices", in theory it is for a string of messages)
/api/generate (this is the one originally used for text, but also returns the prompt tokens)
/api/chat (used for the tools)

Of these we only use the final two.

**Comment by xyproto** [comment]
As far as I can tell `/chat/completions` is only for OpenAI compatibility, so I'm not too worried about not supporting this endpoint, unless it has advantages or possibilities that the other endpoints do not have: https://ollama.com/blog/openai-compatibility

**Comment by xyproto** [comment]
I merged and then adjusted the PR to keep backward compatibility for existing programs and packages that uses the `ollamaclient` package.

**Pull request merged**
